//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HollywoodTest.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbErrorLog
    {
        public long ErrorLogID { get; set; }
        public string ErrorMessage { get; set; }
        public string Source { get; set; }
        public System.DateTime Date { get; set; }
    }
}
