//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HollywoodTest.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEventDetail
    {
        public long EventDetailID { get; set; }
        public long FK_EventID { get; set; }
        public long FK_EventDetailStatusID { get; set; }
        public string EventDetailName { get; set; }
        public short EventDetailNumber { get; set; }
        public decimal EventDetailsOdd { get; set; }
        public short FinishingPosition { get; set; }
        public bool FirstTimer { get; set; }
    
        public virtual tbEvent tbEvent { get; set; }
        public virtual tbEventDetailStatu tbEventDetailStatu { get; set; }
    }
}
